name: NPM Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
          access: public
